// Settings
export const SET_UNIT = 'SET_UNIT';
export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_TIME_TYPE = 'SET_TIME_TYPE';
export const SET_ACTIVE_LOCATION = 'SET_ACTIVE_LOCATION';
export const SET_ONBOARDING = 'SET_ONBOARDING';
export const UPDATE_LATEST_TIMESTAMP = 'UPDATE_LATEST_TIMESTAMP';

// Locations
export const SET_LOCATION = 'SET_LOCATION';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS';
export const ADD_LOCATION_ERROR = 'ADD_LOCATION_ERROR';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const ADD_INDEX_LOCATION = 'ADD_INDEX_LOCATION';
export const LOCATION_LOADING = 'LOCATION_LOADING';
export const LOCATION_LOADING_OFF = 'LOCATION_LOADING_OFF';

// Fetch All Locations
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';

// Location Errors
export const SET_ACTIVE_LOCATION_ERROR = 'SET_ACTIVE_LOCATION_ERROR';
export const ADD_INDEX_LOCATION_ERROR = 'ADD_INDEX_LOCATION_ERROR';
export const UPDATE_ERROR = 'UPDATE_ERROR';
